CREATE TABLE client (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    CONSTRAINT client_name_length_chk
        CHECK (LENGTH(name) BETWEEN 3 AND 200)
);

CREATE TABLE planet (
    id   VARCHAR(50)  NOT NULL,
    name VARCHAR(500) NOT NULL,
    CONSTRAINT planet_pk PRIMARY KEY (id),
    CONSTRAINT planet_id_format_chk
        CHECK (REGEXP_LIKE(id, '^[A-Z0-9]+$')),
    CONSTRAINT planet_name_length_chk
        CHECK (LENGTH(name) BETWEEN 1 AND 500)
);

CREATE TABLE ticket (
    id             BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    client_id      BIGINT                   NOT NULL,
    from_planet_id VARCHAR(50)              NOT NULL,
    to_planet_id   VARCHAR(50)              NOT NULL,

    CONSTRAINT ticket_client_fk
        FOREIGN KEY (client_id) REFERENCES client(id),
    CONSTRAINT ticket_from_planet_fk
        FOREIGN KEY (from_planet_id) REFERENCES planet(id),
    CONSTRAINT ticket_to_planet_fk
        FOREIGN KEY (to_planet_id) REFERENCES planet(id),

    CONSTRAINT ticket_different_planets_chk
        CHECK (from_planet_id <> to_planet_id)
);

CREATE INDEX ticket_client_idx      ON ticket(client_id);
CREATE INDEX ticket_from_planet_idx ON ticket(from_planet_id);
CREATE INDEX ticket_to_planet_idx   ON ticket(to_planet_id);